# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba19a5d5cd1d3ab0ab266440168e47367c2c2d30b38b79180ad0a93b41ee4df390f7bf260189e224bf492b5706dacca52b29c906b2abbdb16526a14e4355394d

test:
  secret_key_base: 2b536ff6889dadb782f3dfc77547c61eaf1c66dea2109a18a834cc952122b69c2c609569bc2d23ae8e5b186ad8183d75da179059d2d435ab9ea0e31e7c280ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
